### ISSUE TITLE
6 digits for alleles

### ISSUE THREAD

**Issue by vanihla5** [felixfan/PyHLA#6]
Number of digits that can be entered for all the alleles should be 4 or 6 as said in the manual. If an allele like A*24:11N or A*02:131 is present and all the other alleles are in 6 digits, how do I do the analysis for 6 digits? As such, some of the alleles are named only till 4th digit by IMGT or somethimes as 24:11N or 02:131 and so on. Is it not possible to do the analysis for the rest of the 6 digit alleles at 6 digit level in such cases? 
is there a way to code these alleles so that 6 digit analysis can be done?

**Comment by felixfan** [comment]
you can try to code them as 'NA', so they will be ignored.
